[phases.setup]
nixPkgs = ["nodejs", "google-chrome-stable"]

[phases.install]
cmds = ["PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm install"]

[phases.build]
cmds = ["npm run build"]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/google-chrome-stable"
